### ISSUE TITLE
Check for filetype already set (neovim compatibility)

### ISSUE THREAD

**Issue by davidosomething** [cakebaker/scss-syntax.vim#66] opened 2016-07-21 15:29 UTC
Neovim comes with tpope's scss runtimes and already sets the `scss` filetype
Need an update such that the ftdetect will not run if the filetype is already `scss` -- otherwise the `filetype scss` autocommand will run twice (once for neovim filetype.vim and again for scss-syntax.vim's ftdetect)

**Comment by cakebaker** [comment] 2016-08-08 13:19
Hm, I'm not sure I understand what the issue is...

I checked <code>filetype.vim</code> and https://github.com/cakebaker/scss-syntax.vim/blob/master/ftdetect/scss.vim and noticed that the first line in scss.vim
```
au BufRead,BufNewFile *.scss set filetype=scss
```
is probably redundant as it is already set in <code>filetype.vim</code>. Is that the issue you refer to or do you mean something else?

**Comment by davidosomething** [comment] 2016-08-08 17:47
Yea that's it, I think it is safer to use the non-override form `setfiletype` instead of `set filetype` to avoid possible double-trigger or overriding user settings from .vimrc/init.vim

```
B. If you want to detect your file after the default file type checks.

   This works like A above, but instead of setting 'filetype' unconditionally
   use ":setfiletype".  This will only set 'filetype' if no file type was
   detected yet.  Example: >
	au BufRead,BufNewFile *.txt		setfiletype text
```

**Comment by cakebaker** [comment] 2016-08-09 08:32
Ok, fixed in https://github.com/cakebaker/scss-syntax.vim/commit/4461789d02f81fd328afbdf27d6404b6c763c25f. Thanks for reporting.

**Closed by cakebaker** 2016-08-09 08:32 UTC
