### ISSUE TITLE
Comments inside method definition not being highlighted

### ISSUE THREAD

**Issue by alem0lars** [cakebaker/scss-syntax.vim#60] opened 2015-03-24 15:31 UTC
The screenshot below shows the problem:
- `// {{{` isn't highlighted

![screen shot 2015-03-24 at 16 30 00](https://cloud.githubusercontent.com/assets/336957/6805432/3167d6b2-d243-11e4-8e59-ce99fe8913e7.png)

**Comment by alem0lars** [comment] 2015-03-24 16:11
Also, `// {{{` isn't recognized when used normally..

![screen shot 2015-03-24 at 17 10 37](https://cloud.githubusercontent.com/assets/336957/6806398/ca4a78b2-d248-11e4-9406-697750f5bf2e.png)

**Comment by cakebaker** [comment] 2015-03-25 08:42
The first issue is fixed in https://github.com/cakebaker/scss-syntax.vim/commit/a05f91d4e4a13d36bbefe4134207d46b9271ab37. However, I'm unable to reproduce the second issue. After adding the following lines to your <code>.vimrc</code>:
```
set laststatus=2
set statusline+=%{synIDattr(synID(line('.'),col('.'),1),'name')}
```
What is shown when your cursor is over the comment? The expected value is <code>scssComment</code>.

**Comment by alem0lars** [comment] 2015-03-25 08:49
I see:
* Inside `// {{`: `scssSelector`
* Inside the third curly brace: `cssBraces`
* Inside the rest of the line: `scssDefinition`

**Comment by cakebaker** [comment] 2015-03-25 09:23
Ok, I can reproduce the issue, though only if the comment is inside a mixin.

**Comment by cakebaker** [comment] 2015-03-26 07:22
Fixed in https://github.com/cakebaker/scss-syntax.vim/commit/be70ea8d205660b5fb67fd6a37b43d626b1ebe29. Thanks for reporting these issues!

**Closed by cakebaker** 2015-03-26 07:22 UTC
