### ISSUE TITLE
Some properties are (incorrectly) highlighted as errors

### ISSUE THREAD

**Issue by alem0lars** [cakebaker/scss-syntax.vim#51] opened 2015-02-24 10:01 UTC
As you can see in the screenshot below, sometimes properties are highlighted as errors, but they are correct properties (like `font-size`, etc..)

![napkin napkin 24-02-15 10 54 33 am](https://cloud.githubusercontent.com/assets/336957/6346942/3fc911c0-bc14-11e4-994b-f3a7895ec143.png)

**Comment by cakebaker** [comment] 2015-02-25 07:04
I'm unable to reproduce this issue. Somehow I think there is some difference between your Vim environment and mine, considering I'm unable to reproduce #47, #50 and this ticket...

**Comment by alem0lars** [comment] 2015-02-25 07:32
I get that error (red background highlight) only if I set:
```VimL
autocmd FileType scss set iskeyword+=-
```

Otherwise I see the properties not highlighted (as `margin-top` in that screenshot), but I think that is the bug #50.

BTW the issue #47 is fixed and it works correctly now :)

I attach a gist of the file related to the screenshot so you can test against the whole file content: [https://gist.github.com/alem0lars/95ab3bfd7dd8484de5f0](https://gist.github.com/alem0lars/95ab3bfd7dd8484de5f0)

Thanks for the support.

**Comment by cakebaker** [comment] 2015-02-28 15:52
Closing this ticket as the issue has the same cause as #50.

**Closed by cakebaker** 2015-02-28 15:52 UTC
