### ISSUE TITLE
Incorrect highlighting for commented selector

### ISSUE THREAD

**Issue by alem0lars** [cakebaker/scss-syntax.vim#62] opened 2015-03-30 19:32 UTC
If you try to comment a selector, the comment syntax isn't recognized..
See the screenshots below:

![screen shot 2015-03-30 at 11 21 38](https://cloud.githubusercontent.com/assets/336957/6904876/3e94cf80-d724-11e4-93f7-09c00eb86d22.png)
![screen shot 2015-03-30 at 11 21 55](https://cloud.githubusercontent.com/assets/336957/6904877/3eb7753a-d724-11e4-8960-73bc94e7701d.png)

Thanks

**Comment by cakebaker** [comment] 2015-03-31 05:33
Hm, I'm unable to reproduce the issue here. Is this code snippet inside another element like e.g. a mixin? And what is shown for the incorrectly highlighted comment when you add the following two lines to your <code>.vimrc</code>?
```
set laststatus=2
set statusline+=%{synIDattr(synID(line('.'),col('.'),1),'name')}
```

**Comment by alem0lars** [comment] 2015-03-31 06:39
Both in the line `//html##{$ns} {` and `//  abbr:hover {` gives me:
* Before and hover `//`: `scssSelector`
* After `//`: `cssTagName`

![screen shot 2015-03-31 at 08 36 16](https://cloud.githubusercontent.com/assets/336957/6913479/2b0c95ee-d781-11e4-8846-4b504f4d1910.png)

**Comment by cakebaker** [comment] 2015-03-31 08:44
Thanks, though I'm still unable to reproduce it :|

**Comment by alem0lars** [comment] 2015-03-31 11:46
Try with this file:
```
@charset "utf-8";


// {{{ Public methods.

//
// Apply clearfix after all children elements.
//
@mixin clearfix() {
  //&:after {
  //  display:    block;
  //  height:     0;
  //  clear:      both;
  //  font-size:  0;
  //  content:    " ";
  //  visibility: hidden;
  //}
}

//
// Apply floating to the enclosing element.
//
@mixin float() {
  float: left;
}

// }}}
```

**Comment by cakebaker** [comment] 2015-03-31 14:20
It works fine here. 

Is it possible you're using an older version of the syntax file? If I undo a change made for #60 (commit https://github.com/cakebaker/scss-syntax.vim/commit/be70ea8d205660b5fb67fd6a37b43d626b1ebe29) I get the issues you describe.

**Comment by cakebaker** [comment] 2015-04-07 14:18
Closing this ticket as I think it's a duplicate of #60. Please re-open if the issue still exists.

**Closed by cakebaker** 2015-04-07 14:18 UTC
